# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRxSILV8IdUnYTHpTOQJhyVNJAu0IAFw
"""

from fastapi import FastAPI, HTTPException, Header
from tensorflow.keras.models import load_model
import numpy as np

app = FastAPI()

# Load the LSTM model at startup
lstm_model = load_model('/content/lstm_model.keras')

API_KEY = "YOUR_SECRET_KEY"  # Replace with a secure key

def authenticate(api_key: str):
    if api_key != API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API Key")

@app.post("/predict")
def predict(data: dict, api_key: str = Header(...)):
    authenticate(api_key)
    # Expects {"inputs": [[...]]}
    X = np.array(data["inputs"])
    preds = lstm_model.predict(X)
    return {"prediction": preds.tolist()}